version: '3.8'

services:
  # Backend Laravel
  auth-backend:
    build: ./backend
    container_name: auth-backend
    ports:
      - "8001:8000"
    environment:
      - DB_HOST=db-auth
      - DB_DATABASE=authdb
      - DB_USERNAME=auth_user
      - DB_PASSWORD=auth_password
      - JWT_SECRET=your-super-secret-jwt-key
    depends_on:
      - db-auth
    networks:
      - auth-network
    volumes:
      - ./backend:/var/www

  # Frontend Angular
  auth-frontend:
    build: ./frontend
    container_name: auth-frontend
    ports:
      - "4201:4200"
    environment:
      - API_URL=http://localhost:8001/api
    networks:
      - auth-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Banco de Dados MariaDB
  db-auth:
    image: mariadb:10.6
    container_name: db-auth
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=authdb
      - MYSQL_USER=auth_user
      - MYSQL_PASSWORD=auth_password
    ports:
      - "3307:3306"
    networks:
      - auth-network
    volumes:
      - auth-data:/var/lib/mysql

  # MailHog para testes de email
  mailhog:
    image: mailhog/mailhog
    container_name: auth-mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - auth-network

volumes:
  auth-data:

networks:
  auth-network:
    driver: bridge