version: '3.8'

services:
  # Backend Laravel
  auth-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: auth-backend
    ports:
      - "8000:8000"
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=auth-db
      - DB_PORT=3306
      - DB_DATABASE=auth_db
      - DB_USERNAME=auth_user
      - DB_PASSWORD=auth_password
      - JWT_SECRET=your-super-secret-jwt-key-here-change-in-production
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:your-app-key-here
    depends_on:
      - auth-db
    networks:
      - auth-network
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
      - /var/www/html/node_modules

  # Frontend Angular
  auth-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: auth-frontend
    ports:
      - "4200:4200"
    environment:
      - API_URL=http://localhost:8000/api
    networks:
      - auth-network
    volumes:
      - ./frontend:/app
      - /app/node_modules

  # Banco de Dados MariaDB
  auth-db:
    image: mariadb:10.9
    container_name: auth-db
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=auth_db
      - MYSQL_USER=auth_user
      - MYSQL_PASSWORD=auth_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
      - auth-network

  # phpMyAdmin (opcional, para desenvolvimento)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: auth-phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=auth-db
      - PMA_USER=auth_user
      - PMA_PASSWORD=auth_password
    depends_on:
      - auth-db
    networks:
      - auth-network

volumes:
  auth_db_data:

networks:
  auth-network:
    driver: bridge