services:
  auth-service:
    build: ./auth/backend
    ports:
      - "3001:8000"
    environment:
      - DB_HOST=db-auth
      - DB_DATABASE=authdb
      - DB_USERNAME=auth_user
      - DB_PASSWORD=auth_password
      - JWT_SECRET=supersecretkey
    depends_on:
      - db-auth
    networks:
      - app-network

  auth-frontend:
    build: ./auth/frontend
    ports:
      - "4001:4200"
    environment:
      - API_URL=http://auth-service:8000/api
    networks:
      - app-network

  db-auth:
    image: mariadb:10.6
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=authdb
      - MYSQL_USER=auth_user
      - MYSQL_PASSWORD=auth_password
    volumes:
      - auth-data:/var/lib/mysql
    networks:
      - app-network